### ISSUE TITLE
Durability to 0 Issues.

### ISSUE THREAD

**Issue by KaneHart** [CrimsonFluff/Simple-Magnet#2]
I might be crazy and this was MP. But when I had tested to setting Durability to 0 the pre crafted Magnet worked so I went with it. Now fast forward to my actual server and it's not working crafting it from scratch.

I'm wondering if you can confirm crafting the magnet from scratch with 0 durability is indeed broken?

Thanks :)

**Comment by CrimsonFluff** [comment]
which version are you using because Forge shouldn't allow 0 durability. Also this is not a creative magnet. It requires a durability to work

If you require a cheat magnet use a mod like Pickle Tweaks or Botania

**Comment by KaneHart** [comment]
Thanks, I will stay with the older version hehe. So I derped up bad... It was working Just fine... I had no clue there was shift to do the modes then none shift to turn it on and off and I never actually turned it on derp haha.

Thanks either ways for giving me your super easy recipe ;) I went ahead and nerfed it more :P
